### ISSUE TITLE
inerail.net mirrors are failing

### ISSUE THREAD

**Issue by willard-dawson-nyl** [pentoo/pentoo-installer#11]
While this does not prevent Pentoo installation from the latest livecd, it slows it down due to the repeated failure/retry attempts to update due to coded BINHOST settings pointing to the inerail.net hosts that are not responding over the past several days.

Cloudflare reports:
Error 522 Ray ID: 2a9b4f129d693882 • 2016-05-27 17:50:38 UTC
Connection timed out

**Comment by ZeroChaos-** [comment]
this is sad, but is has been solved (we don't use them anymore) and has nothing to do with pentoo-installer

**Comment by blshkv** [comment]
Somehow, the mirror list was not updated on RC5. So just update overlay:
```
layman -S
env-update && source /etc/profile
emerge -1 pentoo-installer
```
