### ISSUE TITLE
pentoo-installer - grub.conf

### ISSUE THREAD

**Issue by ostree** [pentoo/pentoo-installer#14]
Hello,

to install grub on the local hard drive I had to manually:

touch /mnt/gentoo/boot/grub.conf

after the synchronization of the content from the livecd. Otherwise grub installation will fail,

regards

**Comment by blshkv** [comment]
have you tried the latest, i.e. emerge -1 pentoo-installer before installing?

**Comment by blshkv** [comment]
Unable to reproduce. Either install the latest installer or grap the latest iso from http://www.pentoo.ch/isos/Beta. Please reopen the bug if you still see it.
