### ISSUE TITLE
pentoo-installer - boot not mounted

### ISSUE THREAD

**Issue by ostree** [pentoo/pentoo-installer#15]
Hello,

over the installation I can see that there is no dedicated boot partition mounted. I can see that this is due to lack of /boot folder - installer failed to create this folder. When checking with mount command partition seams to be mounted but due to lack of the boot folder an installation will be completed to the /boot folder of the / (root) partition. This in return in the encrypted setup will render system unbootable.

partitions layout(mbr):
sda1 boot
sda2 swap (encrypted)
sda3 root (encrypted)

regards

**Comment by blshkv** [comment]
Unable to reproduce. Either install the latest installer or grap the latest iso from http://www.pentoo.ch/isos/Beta. Please reopen the bug if you still see it.
