### ISSUE TITLE
20161025.iso rename host does not work

### ISSUE THREAD

**Issue by blshkv** [pentoo/pentoo-installer#17]
There is a "rename hostname" menu during the installation.
I entered a new hostname but it did not change the default name (pentoo).

**Comment by Wuodan** [comment]
Worked here on 2018 rc 7.2.
Please describe your steps when running the installer.

**Comment by blshkv** [comment]
Just install normally, and choose rename host menu once you reached this point

**Comment by ZeroChaos-** [comment]
it is working for /etc/conf.d/hostname but seems there is something wrong with /etc/hosts setting

Also of note, it only works the first time you run it, if you run it again the first hostname will remain.  Improvement needed.

**Comment by ZeroChaos-** [comment]
improvement made
https://github.com/pentoo/pentoo-installer/commit/60a297d632db152fcdfa088f3a1f01b5c60cf48f
