### ISSUE TITLE
/etc/timezone missing after install

### ISSUE THREAD

**Issue by Wuodan** [pentoo/pentoo-installer#19]
maybe it was the syncing of ISO changes ... although there weren't any relevant, just emerge --synd and update installer.
Will look at it next time.

**Comment by Wuodan** [comment]
Same for changes to /etc/conf.d/hwclock, they are missing.

From memory: The installer asks for these 2 settings at the very beginning when nothing is mounted.
I think the installer should store these settings somewhere and apply at a later stage.
Something in that chain is now going wrong or missing.

**Comment by Wuodan** [comment]
pls approve PR to fix this #28 tnx

**Comment by blshkv** [comment]
Please test and let us know if any further issues
