### ISSUE TITLE
Errors in grub2 installation ignored

### ISSUE THREAD

**Issue by Wuodan** [pentoo/pentoo-installer#21]
[grub.log](https://github.com/pentoo/pentoo-installer/files/2077612/grub.log)
**pentoo-installer issue:**
The 2 lines 196 and 203 in
/usr/share/pentoo-installer/bootloader_grub2
do not end with

>  || exit $?

thus errors in grub2-install are ignored.

**Text below is not relevant to pentoo-installer !!**

Description of error with log (should/will open a bugzilla issue):
line 196 calls grub2-install:

> chroot "${DESTDIR}" /usr/sbin/grub2-install -v --efi-directory=/boot --bootloader-id=Pentoo --themes=pentoo --recheck "${DISK_BOOT}" >/tmp/grub.log 2>&1

efibootmgr -v output before grub2-install:

> pentoo /usr/share/pentoo-installer # efibootmgr -v
BootCurrent: 001A
Timeout: 0 seconds
BootOrder: 0000,0016,0017,0018,0019,001A,001B
Boot0000* Windows Boot Manager	HD(1,GPT,0d03d364-463b-49d2-b645-0d899cdf0ed8,0x800,0x82000)/File(\EFI\Microsoft\Boot\bootmgfw.efi)WINDOWS.........x...B.C.D.O.B.J.E.C.T.=.{.9.d.e.a.8.6.2.c.-.5.c.d.d.-.4.e.7.0.-.a.c.c.1.-.f.3.2.b.3.4.4.d.4.7.9.5.}...B................
Boot0010  Setup	FvFile(721c8b66-426c-4e86-8e99-3457c46ab0b9)
Boot0011  Boot Menu	FvFile(126a762d-5758-4fca-8531-201a7f57f850)
Boot0012  Diagnostic Splash Screen	FvFile(a7d8d9a6-6ab0-4aeb-ad9d-163e59a7a380)
Boot0013  Lenovo Diagnostics	FvFile(3f7e615b-0d45-4f80-88dc-26b234958560)
Boot0014  Startup Interrupt Menu	FvFile(f46ee6f4-4785-43a3-923d-7f786c3c8479)
Boot0015  Rescue and Recovery	FvFile(665d3f60-ad3e-4cad-8e26-db46eee9f1b5)
Boot0016* USB CD	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,86701296aa5a7848b66cd49dd3ba6a55)
Boot0017* USB FDD	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,6ff015a28830b543a8b8641009461e49)
Boot0018* NVMe0	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,001c199932d94c4eae9aa0b6e98eb8a400)
Boot0019* ATA HDD0	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,91af625956449f41a7b91f4f892ab0f600)
Boot001A* USB HDD	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,33e821aaaf33bc4789bd419f88c50803)
Boot001B* PCI LAN	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,78a84aaf2b2afc4ea79cf5cc8f3d3803)

Relevant error in grub output:

> /usr/sbin/grub2-install: info: executing efibootmgr -c -d /dev/nvme0n1 -p 1 -w -L Pentoo -l \EFI\Pentoo\grubx64.efi.
Skipping unreadable variable "Boot0001": Input/output error
Skipping unreadable variable "Boot0002": Input/output error
Could not prepare Boot variable: Input/output error
Installation finished. No error reported.

**Comment by Wuodan** [comment]
problem does not occur when installing to USB-stick (/dev/sdb)
[grub.log](https://github.com/pentoo/pentoo-installer/files/2081895/grub.log)

**Comment by ZeroChaos-** [comment]
fab91b9cafbea99444214ecc12530bac8115cb4b
