### ISSUE TITLE
efibootmgr: option requires an argument -- 'b'

### ISSUE THREAD

**Issue by Wuodan** [pentoo/pentoo-installer#24]
Installer doesn't fail, but I wasted a lot of time thinking this was the cause.
3 code lines  like:
efibootmgr -B -b $(efibootmgr | grep Pentoo | awk -F'*' '{print $1}' | cut -b 5-8)
in:
/usr/share/pentoo-installer/bootloader_grub2
will print this error when grub finds nothing.

About to write a patch just cause it drove me crazy.

**Comment by Wuodan** [comment]
Please forget the the first commit, the second is what I would like to change, tnx

**Comment by blshkv** [comment]
Didn't see your comment. Please verify

**Comment by Wuodan** [comment]
Verified on 2018 rc7.2
