### ISSUE TITLE
Bluetooth: Failed to apply network settings

### ISSUE THREAD

**Issue by Wuodan** [pentoo/pentoo-installer#25]
After installation (amd64 hardened), on first 'startx' by pentoo user, I'm greeted by this error:

**Failed to apply network settings**
You might not be able to connect to the Bluetooth network via this machine
**Exception**
g-io-error-quark: GDBus.Error:org.freedesktop.DBus.Python.dbus.exceptions.DBusException: Blueman was built with PolicyKit-1 support, but it's not available on the system (36)

This error does not pop up when booting the LiveUSB

**Comment by Wuodan** [comment]
It only happened on first startx with pentoo user on rc7.1
I don't think it happened on rc7.2 ... but am not sure. Keeping this open to verify next time.

**Comment by ZeroChaos-** [comment]
this was caused by the /var/lib permissions being wrong, which you already fixed.
