### ISSUE TITLE
gpg-agent: fails with pin-entry-qt (default after installation)

### ISSUE THREAD

**Issue by Wuodan** [pentoo/pentoo-installer#30]
> $ git commit -S -m "accept_keywords: vmtools needs xml-security-c"
> error: gpg failed to sign the data
> fatal: failed to write commit object

tty1 also prints this:
> gpg-agent[3990]: can't connect to the PIN entry module '/usr/bin/pinentry' : End of file

The problem is pinentry-qt:
> $ eselect pinentry list
> [1]   pinentry-qt *
>   [2]   pinentry-gtk-2
>   [3]   pinentry-qt4
>   [4]   pinentry-curses
>   [5]   pinentry-tty

The only option that works in xfce4-terminal is pinentry-gtk-2:
> eselect pinentry set 2
then the pinentry gui pops up as expected.

Think I did not have to do this with last installation with ISO from a few months ago, so this seems new behavior.

**Comment by Wuodan** [comment]
This is annoying ... I hate when I write a long commit message and then lose it because pinentry fails !!!

**Comment by blshkv** [comment]
This is strange because both interfaces gtk and qt works in KDE env. It would only use a different backend

**Comment by ZeroChaos-** [comment]
they really *should* both work, but I need to rewrite this anyway for supporting the best default when we build kde isos.  i'll fix it up in a little bit here

**Comment by ZeroChaos-** [comment]
set during installer
8cc852eb23f74a3212b53b56f3635e76bf9ab806

**Comment by ZeroChaos-** [comment]
also added this to fsscript during livecd generation so it's set on livecd, reset when pentoo-installer runs, then set on the install system.  setting three times should be enough
