### ISSUE TITLE
Installer fails on flushchanges file

### ISSUE THREAD

**Issue by Wuodan** [pentoo/pentoo-installer#51]
The installer fails when flushchanges was used before running the installer:
![pentoo-installer_failsWithFlushchangeFiles](https://user-images.githubusercontent.com/1812358/83322974-d9526200-a25b-11ea-84ed-03489a2cf999.png)

These **comments** in the code in /usr/share/pentoo-installer/copy_distro are interesting:
`squashfs files created by flushchanges are ignored - they may contain whiteout files!
filenames used by flushchanged (old/new syntax): z_changes-* zz_changes-*`

followed by these 3 lines of **code**:

> for MODULE in $(ls -1 --color=never /mnt/cdrom/modules/*.lzm); do
    "${SHAREDIR}"/gauge_unsquashfs "${MODULE}" "${DESTDIR}" "Uncompressing ${MODULE%.lzm}" || exit $?
done

**Question:**
Shall the installer ignore the flushchanges files?

**Comment by ZeroChaos-** [comment]
That failure doesn't give much to work with.  It should work safely afaik, but also the full rsync option would handle it.  Maybe we should just detect changes saving files and do a full rsync?
