### ISSUE TITLE
mokmanager efi image is sometimes required in /boot/efi/boot

### ISSUE THREAD

**Issue by Wuodan** [pentoo/pentoo-installer#52]
After running the installer, uefi fails to find the mokmanager efi image.
On latest iso (pentoo-full-x86-hardened-2020.0_p20200527.iso).
![20200531_185722](https://user-images.githubusercontent.com/1812358/83359540-553ad000-a36a-11ea-9c36-b499b292cdc4.jpg)

This was working before and I don't know what changed.
I manually copied the file mmx64.efi to /boot/efi/boot and then it worked.

Proposal:
copy the mokmanager files to both /boot/efi/Pentoo and /boot/efi/boot
Am testing it right now, pull-request will follow

**Comment by ZeroChaos-** [comment]
You really shouldn't need mokmamager after install but yeah, sure, I can do that.
