### ISSUE TITLE
if ever upstream supports openrc... (calamares)

### ISSUE THREAD

**Issue by necrose99** [pentoo/pentoo-installer#9]
https://github.com/necrose99/calamares-pentoo-branding

for now I have a few pretty slides that would run during install , mainly tinkering with artwork 
but anyone's welcome to meddle. 

pentoo-test-system   ebuild , ie fork of pentoo-system and systemD for testing 
works on sabayon and sabayon fork , Rogento/s  

Crypto loop , Openrc zfs , etc support is slowly evolving. 

for now the gui was intended as an augment, 

https://calamares.io/ https://github.com/calamares/calamares

**Comment by lugarius** [comment]
1+

**Comment by ZeroChaos-** [comment]
this bug tracker is for the pentoo-installer, not switching to some random installer that doesn't even work yet.
